apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30081
  selector:
    app: demo-app
